### ISSUE TITLE
Trick Redis client into using Rlite connection?

### ISSUE THREAD

**Issue by etingof** [seppo0010/rlite-py#4]
I'm looking for a way to make [redis-py](https://github.com/WoLpH/redis-py/) using rlite database file instead of Redis server by replacing the [database connection](https://github.com/WoLpH/redis-py/blob/master/redis/connection.py#L167) object.

Alternatively, I could try mimicing [Redis](https://github.com/WoLpH/redis-py/blob/master/redis/client.py#L135) client on the basis of Rlite client, which is probably more logical, but also more engaging. Additional complication is that some applications out there (Python-RQ) are hardwired to use Redis class, so they would notice and reject alien database client then.

Would it make sense to ship rlite-py with some redis-py API compatibility provisions to make rlike-py a drop-in replacement for Redis client?

What would be your recommendation, how I'd better approach my task?

**Comment by seppo0010** [comment]
I think replacing the database connection object is the way to go. rlite-py already provides a similar API, so it needs to be just a thin wrapper (e.g.: `send_command` should call rlite-py's `command`, push the response to a queue and pop elements on `read_response`).

I don't have the time now to do the work, but if you submit a PR that would make it easier for people using rlite-py to do so, I'll merge it.
